name: nlp
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.6.1=py36_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - boto=2.49.0=py36_0
  - boto3=1.9.199=py_0
  - bz2file=0.98=py36_1
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py36_0
  - cffi=1.11.5=py36he75722e_1
  - chardet=3.0.4=py36_1
  - cryptography=2.3.1=py36h1ba5d50_2
  - cudatoolkit=9.2=0
  - cudnn=7.6.0=cuda9.2_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py36_0
  - cymem=1.31.2=py36h6bb024c_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.0=py36_0
  - dill=0.2.8.2=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.0=py36_0
  - gensim=3.4.0=py36h14c3975_0
  - glib=2.56.2=hd408876_0
  - grpcio=1.12.1=py36hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h211956c_0
  - idna=2.7=py36_0
  - intel-openmp=2019.0=118
  - ipykernel=5.0.0=py36h39e3cac_0
  - ipython=7.0.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.13.1=py36_0
  - jpeg=9b=habf39ab_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.0.1=py36_0
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2019.0=118
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - msgpack-numpy=0.4.4.1=py36_0
  - msgpack-python=0.5.6=py36h6bb024c_1
  - murmurhash=0.28.0=py36hf484d3e_0
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py36h6bb024c_1
  - nltk=3.3.0=py36_0
  - numpy=1.15.1=py36h1d66e8a_0
  - numpy-base=1.15.1=py36h81de0dd_0
  - openssl=1.1.1c=h516909a_0
  - pandas=0.23.4=py36h04863e7_0
  - parso=0.3.1=py36_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=10.0.1=py36_0
  - plac=0.9.6=py36_0
  - preshed=1.0.1=py36he6710b0_0
  - prompt_toolkit=2.0.6=py36_0
  - protobuf=3.6.1=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pysocks=1.6.8=py36_0
  - python=3.6.7=h0371630_0
  - python-dateutil=2.7.3=py36_0
  - pytorch=1.2.0=py3.6_cuda9.2.148_cudnn7.6.2_0
  - pytorch-pretrained-bert=0.6.2=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - regex=2018.07.11=py36h14c3975_0
  - requests=2.19.1=py36_0
  - s3transfer=0.2.1=py36_0
  - scikit-learn=0.20.0=py36h4989274_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - seaborn=0.9.0=py36_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.13=py36he6710b0_0
  - six=1.11.0=py36_1
  - smart_open=1.8.4=py_0
  - spacy=2.0.12=py36h962f231_0
  - sqlite=3.26.0=h7b6447c_0
  - statsmodels=0.10.1=py36hdd07704_0
  - tensorboard=1.11.0=py36hf484d3e_0
  - tensorflow=1.11.0=gpu_py36h9c9050a_0
  - tensorflow-base=1.11.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.11.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - thinc=6.10.3=py36h962f231_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h7b6447c_0
  - tqdm=4.26.0=py36h28b3542_0
  - traitlets=4.3.2=py36_0
  - ujson=1.35=py36h14c3975_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - wrapt=1.10.11=py36h14c3975_2
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h96e3832_1
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - pip:
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - botocore==1.8.36
    - bpemb==0.3.0
    - deprecated==1.2.6
    - docutils==0.14
    - flair==0.4.2
    - future==0.17.1
    - hyperopt==0.1.2
    - importlib-metadata==0.23
    - jieba==0.42.1
    - jmespath==0.9.3
    - keras-contrib==2.0.8
    - more-itertools==7.2.0
    - mpld3==0.3
    - networkx==2.3
    - packaging==19.1
    - pluggy==0.13.0
    - py==1.8.0
    - pyasn1==0.4.4
    - pydot==1.4.1
    - pymongo==3.9.0
    - pytest==5.1.2
    - pytorch-nlp==0.4.1
    - rsa==3.4.2
    - segtok==1.5.7
    - sentencepiece==0.1.83
    - sklearn==0.0
    - sqlitedict==1.6.0
    - tabulate==0.8.3
    - zipp==0.6.0
prefix: /home/larry5/.conda/envs/nlp

